export default [
    {
        title: "Grand Canyon",
        location: "USA",
        googleMapsUrl: "https://goo.gl/maps/7R9fDhGvNyn",
        startDate: "5 Mar, 2021",
        endDate: "15 Mar, 2021",
        description: "The Grand Canyon is a steep-sided canyon carved by the Colorado River in Arizona, USA. It is known for its visually overwhelming size and its intricate and colorful landscape.",
        imageUrl: "https://images.unsplash.com/photo-1543266502-7a301a17e75e?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: 1,
    },
    {
        title: "Eiffel Tower",
        location: "France",
        googleMapsUrl: "https://goo.gl/maps/Y6zUq",
        startDate: "20 Apr, 2021",
        endDate: "25 Apr, 2021",
        description: "The Eiffel Tower, located in Paris, France, is one of the most recognizable structures in the world. It was completed in 1889 and remains a global cultural icon of France.",
        imageUrl: "https://images.unsplash.com/photo-1570939274717-7eda259b50ed?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: 2,
    },
    {
        title: "Great Wall of China",
        location: "China",
        googleMapsUrl: "https://goo.gl/maps/3GfnEz9sYkA2",
        startDate: "1 Oct, 2021",
        endDate: "15 Oct, 2021",
        description: "The Great Wall of China is a series of fortifications made of stone, brick, tamped earth, and other materials, built along the northern borders of China to protect against invasions.",
        imageUrl: "https://images.unsplash.com/photo-1558981017-9c65fb6f2530?q=80&w=1336&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: 3,
    },
    {
        title: "Sydney Opera House",
        location: "Australia",
        googleMapsUrl: "https://goo.gl/maps/6hX9y2KwLT82",
        startDate: "10 Nov, 2021",
        endDate: "20 Nov, 2021",
        description: "The Sydney Opera House is a multi-venue performing arts centre at Sydney Harbour in Sydney, New South Wales, Australia. It is one of the 20th century's most famous and distinctive buildings.",
        imageUrl: "https://images.unsplash.com/photo-1704788623366-8cd4d7285e60?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: 4,
    },
    {
        title: "Christ the Redeemer",
        location: "Brazil",
        googleMapsUrl: "https://goo.gl/maps/fyAfmdBV9qC2",
        startDate: "15 Dec, 2021",
        endDate: "25 Dec, 2021",
        description: "Christ the Redeemer is an iconic statue of Jesus Christ in Rio de Janeiro, Brazil. It was completed in 1931 and stands 30 meters tall on the peak of the 700-meter Corcovado mountain.",
        imageUrl: "https://images.unsplash.com/photo-1580915469312-1eeaaf551731?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        id: 5,
    },
];
